import { validateLoopTaskContract, type LoopTaskContract } from "./task-contract.js";

export const LOOP_CONTRACT_START = "<!-- loop-contract:start -->";
export const LOOP_CONTRACT_END = "<!-- loop-contract:end -->";
export const LOOP_READY_LABEL = "loop:ready";
export const LOOP_DRAFT_LABEL = "loop:draft";
export const LOOP_REVIEW_READY_LABEL = "loop:review-ready";
export const LOOP_RUNNING_LABEL = "loop:running";
export const LOOP_BLOCKED_LABEL = "loop:blocked";
export const LOOP_COMPLETE_LABEL = "loop:complete";
export const LOOP_FAILED_LABEL = "loop:failed";

export const LOOP_LIFECYCLE_LABELS = [
  LOOP_DRAFT_LABEL,
  LOOP_READY_LABEL,
  LOOP_RUNNING_LABEL,
  LOOP_REVIEW_READY_LABEL,
  LOOP_BLOCKED_LABEL,
  LOOP_COMPLETE_LABEL,
  LOOP_FAILED_LABEL,
] as const;

export type LoopGitHubCommandName =
  | "status"
  | "dispatch"
  | "verify"
  | "retry"
  | "stop"
  | "resume"
  | "explain"
  | "review";

export type LoopGitHubCommand = Readonly<{
  command: LoopGitHubCommandName;
  arguments: string;
}>;

export type LoopGitHubIssue = Readonly<{
  number: number;
  title: string;
  body: string | null;
  state: "open" | "closed";
  labels: readonly Readonly<{ name?: string }>[];
}>;

export type LoopGitHubIssueIntake = Readonly<{
  issueNumber: number;
  ready: boolean;
  contract?: LoopTaskContract;
  diagnostics: ReturnType<typeof validateLoopTaskContract>["diagnostics"];
}>;

/** Stable, machine-readable issue body generated by the ChatGPT planning flow. */
export function renderLoopContractBlock(contract: LoopTaskContract): string {
  const validation = validateLoopTaskContract(contract);
  if (!validation.ok) throw new Error("cannot publish an invalid Loop task contract");
  return [
    "## Loop task plan",
    "",
    "This issue is managed by Loop. The contract below is authoritative; surrounding prose is informational.",
    "",
    LOOP_CONTRACT_START,
    JSON.stringify(contract, null, 2),
    LOOP_CONTRACT_END,
  ].join("\n");
}

/** Parse only a standalone @loop command from a GitHub comment. */
export function parseLoopGitHubCommand(body: string | null): LoopGitHubCommand | undefined {
  if (typeof body !== "string") return undefined;
  const line = body
    .split(/\r?\n/)
    .map((entry) => entry.trim())
    .find(Boolean);
  if (!line) return undefined;
  const match =
    /^@loop\s+(status|dispatch|verify|retry|stop|resume|explain|review)(?:\s+(.+))?$/i.exec(line);
  if (!match) return undefined;
  const argumentsValue = match[2]?.trim() ?? "";
  if (argumentsValue.length > 512 || argumentsValue.includes("\0")) return undefined;
  return {
    command: match[1]!.toLowerCase() as LoopGitHubCommandName,
    arguments: argumentsValue,
  };
}

function issueNumber(value: number): number {
  if (!Number.isSafeInteger(value) || value < 1) throw new Error("issue number must be positive");
  return value;
}

/** Extracts only the machine-readable contract block; surrounding prose is untrusted. */
export function extractLoopContractBlock(body: string | null): unknown {
  if (!body) throw new Error("issue body does not contain a Loop contract");
  const start = body.indexOf(LOOP_CONTRACT_START);
  const end = body.indexOf(LOOP_CONTRACT_END, start + LOOP_CONTRACT_START.length);
  if (start < 0 || end < 0 || end <= start)
    throw new Error("Loop contract block is missing or incomplete");
  const raw = body.slice(start + LOOP_CONTRACT_START.length, end).trim();
  if (raw.startsWith("```") && raw.endsWith("```")) {
    const lines = raw.split(/\r?\n/);
    return JSON.parse(lines.slice(1, -1).join("\n"));
  }
  return JSON.parse(raw);
}

export function parseLoopGitHubIssue(issue: LoopGitHubIssue): LoopGitHubIssueIntake {
  const number = issueNumber(issue.number);
  const ready =
    issue.state === "open" && issue.labels.some((label) => label.name === LOOP_READY_LABEL);
  if (!ready) return { issueNumber: number, ready: false, diagnostics: [] };
  let raw: unknown;
  try {
    raw = extractLoopContractBlock(issue.body);
  } catch (error) {
    return {
      issueNumber: number,
      ready: true,
      diagnostics: [
        {
          severity: "error",
          code: "E_CONTRACT_BLOCK",
          path: "body",
          message: error instanceof Error ? error.message : "invalid Loop contract block",
        },
      ],
    };
  }
  if (!raw || typeof raw !== "object" || Array.isArray(raw))
    return {
      issueNumber: number,
      ready: true,
      diagnostics: [
        {
          severity: "error",
          code: "E_CONTRACT_SHAPE",
          path: "body",
          message: "Loop contract must be a JSON object",
        },
      ],
    };
  const contract = raw as LoopTaskContract;
  let validation: ReturnType<typeof validateLoopTaskContract>;
  try {
    validation = validateLoopTaskContract(contract);
  } catch (error) {
    return {
      issueNumber: number,
      ready: true,
      contract,
      diagnostics: [
        {
          severity: "error",
          code: "E_CONTRACT_SHAPE",
          path: "body",
          message: error instanceof Error ? error.message : "contract shape is invalid",
        },
      ],
    };
  }
  return {
    issueNumber: number,
    ready: true,
    contract,
    diagnostics: validation.diagnostics,
  };
}

export function renderLoopStatusComment(
  input: Readonly<{
    taskId: string;
    runId: string;
    generation: number;
    phase: string;
    summary: string;
  }>,
): string {
  if (
    !input.taskId ||
    !input.runId ||
    !Number.isSafeInteger(input.generation) ||
    input.generation < 1
  )
    throw new Error("status comment identity is invalid");
  return [
    `<!-- loop-status task=${input.taskId} run=${input.runId} generation=${input.generation} -->`,
    `## Loop: ${input.phase}`,
    "",
    input.summary,
  ].join("\n");
}
